# Generated by Django 5.1.7 on 2025-03-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_type', models.CharField(choices=[('user', 'User Persona'), ('property', 'Property Persona')], max_length=10)),
                ('persona_data', models.JSONField(help_text='Persona characteristics and information')),
                ('generate_version', models.CharField(help_text='Version of the persona generator', max_length=50)),
                ('prompt_used', models.TextField(blank=True, help_text='The prompt used to generate this persona', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='PropertySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(help_text='LLM-generated property summary')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='Key property highlights')),
                ('generate_version', models.CharField(help_text='Version of the summary generator', max_length=50)),
                ('prompt_used', models.TextField(blank=True, help_text='The prompt used to generate this summary', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Summary',
                'verbose_name_plural': 'Property Summaries',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_version', models.CharField(help_text='Version of the recommendation engine', max_length=50)),
                ('prompt_used', models.TextField(blank=True, help_text='The prompt used to generate recommendations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Recommendation score (higher is better)')),
                ('reasoning', models.TextField(help_text='Why this property was recommended')),
                ('rank', models.PositiveIntegerField(help_text='Ranking position in recommendations')),
            ],
            options={
                'verbose_name': 'Recommendation Item',
                'verbose_name_plural': 'Recommendation Items',
                'ordering': ['rank'],
            },
        ),
    ]
